refactor(fscomponents): remove duplicate export
`./variables` already exports `weights` and metro throws the following error with this conflict in
some circumstances.

```
TypeError: Attempting to change the getter of an unconfigurable property
```

This fixes that.

brandingbrand-source-id: 94589e448e5b49280d05983d11dcdcc18141cf95